# Generated by Django 5.2 on 2025-05-13 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('crime', models.CharField(max_length=50)),
                ('crime_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('arquivado', 'Arquivado'), ('acusado', 'Acusado')], default='pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personcasefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.casefile')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.person')),
            ],
            options={
                'unique_together': {('person', 'casefile')},
            },
        ),
    ]
