# Generated by Django 5.2 on 2025-04-24 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('crime', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('arquivado', 'Arquivado'), ('acusado', 'Acusado')], default='pendente', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
