# Generated by Django 5.2 on 2025-04-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personcasefile',
            old_name='casefile_id',
            new_name='casefile',
        ),
        migrations.RenameField(
            model_name='personcasefile',
            old_name='person_id',
            new_name='person',
        ),
    ]
