# Generated by Django 5.2 on 2025-04-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='casefiles',
        ),
    ]
