# Generated by Django 5.2 on 2025-04-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.CharField(max_length=150),
        ),
    ]
