# Generated by Django 5.2 on 2025-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_casefile_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
