# Generated by Django 5.2 on 2025-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_person_casefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='casefiles', to='records.person'),
        ),
    ]
