# Generated by Django 5.2 on 2025-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_casefile_id_personcasefile_casefile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personcasefile',
            unique_together={('person', 'casefile')},
        ),
    ]
