# Generated by Django 5.2 on 2025-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='number',
        ),
        migrations.AddField(
            model_name='casefile',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
