# Generated by Django 5.2 on 2025-04-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
    ]
