# Generated by Django 5.2 on 2025-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_crimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('arquivado', 'Arquivado'), ('acusado', 'Acusado')], default='pendente', max_length=10),
        ),
    ]
