# Generated by Django 5.2 on 2025-05-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_casefile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.crimetype'),
        ),
    ]
