# Generated by Django 5.2 on 2025-05-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_casefile_crime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='crime',
            field=models.CharField(max_length=50),
        ),
    ]
