# Generated by Django 5.2 on 2025-05-12 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_casefile_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='crime_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
