# Generated by Django 5.2 on 2025-05-12 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_casefile_crime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
