# Generated by Django 5.2 on 2025-05-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_casefile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
